---
title: Useful Resources
author: Janani Ravi
date: '2018-11-12'
slug: useful-resources
categories:
  - Resources
  - R
tags:
  - academic
  - blogs
  - compbio-bioinfo
  - git
  - R
  - refs
  - software-tools
summary: "A lazy mixed post: #academic #bioinformatics #r #blog"
image:
  caption: ''
  focal_point: 'Smart'
---

*My posts with some [#useful-resources](/categories/resources).*

## Great posts | academic
* [The Awesomest 7-year Postdoc *by* Radhika Nagpal | Scientific American](https://blogs.scientificamerican.com/guest-blog/the-awesomest-7-year-postdoc-or-how-i-learned-to-stop-worrying-and-love-the-tenure-track-faculty-life/)
* [Matt Might's Blog](/post/2016/matt-might-blog/)
* [Modeler's Hippocratic oath](/post/2018/modelers-hippocratic-oath)

## Bioinformatics
* [Microbial Bioinformatics Starter Kit *by* Lauren Cowley](https://c2-d2.github.io/hanage-lab/Microbial-Bioinformatics-starter-kit/)
* Microbial genome annotation *by* Michael Eisen
	* [Twitter thread](https://twitter.com/phylogenomics/status/999406494859718662) & [moment](https://twitter.com/i/moments/999641962025074696)
* [Tools for bacterial comparative genomes *by* Holt lab](https://holtlab.net/2015/02/25/tools-for-bacterial-comparative-genomics/)

## R
* [Git, GitHub and R](/post/2018/git-github-links)
* [R resources](https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/) *by* [Paul Vanderlaken](paulvanderlaken.com)
* Related post: [R Tips and Tricks](https://paulvanderlaken.com/2018/05/21/r-tips-and-tricks/)

## Data Visualization
* [Plotting trees + data *by* Holt Lab](https://holtlab.net/2015/10/03/plotting-trees-data/)

## Blogdown, Hugo, Academic & R Markdown
* [Blogdown: Creating websites with R Markdown *by* Yihui Xie](https://bookdown.org/yihui/blogdown/)
* [Hugo](https://github.com/gohugoio)
	* [Hugo discussion forum](https://discourse.gohugo.io/)
* [Hugo Academic *by* George Cushen](https://github.com/gcushen/hugo-academic)
	* [Academic](https://sourcethemes.com/academic/)
* [R Markdown](https://rmarkdown.rstudio.com/index.html)
* [Building your blog using blogdown *by* Marie Dussault](http://mcdussault.rbind.io/post/building-your-blog-using-blogdown/)

## Blogging tips
* [Lifehacker](http://hackerspace.lifehacker.com/top-tips-for-writing-a-blog-post-in-30-minutes-1688838523)
* [6 tips for low-cost academic blogging *by* Matt Might](http://matt.might.net/articles/how-to-blog-as-an-academic/)
* [Ready to start your data science blog? *by* Maëlle Salmon](http://www.masalmon.eu/rladiesct/slides#1)